// <auto-generated />
using BanWho.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanWho.Infrastructure.Migrations
{
    [DbContext(typeof(BanWhoDbContext))]
    partial class BanMeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BanMe.Domain.Entities.BanMeInfo", b =>
                {
                    b.Property<string>("AppVersion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatchUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordedGames")
                        .HasColumnType("int");

                    b.HasKey("AppVersion");

                    b.ToTable("AppInfo");
                });

            modelBuilder.Entity("BanMe.Domain.Entities.ChampGameStats", b =>
                {
                    b.Property<string>("ChampionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("BanRate")
                        .HasColumnType("real");

                    b.Property<int>("Bans")
                        .HasColumnType("int");

                    b.Property<float>("BotPickRate")
                        .HasColumnType("real");

                    b.Property<int>("BotPicks")
                        .HasColumnType("int");

                    b.Property<float>("BotWinRate")
                        .HasColumnType("real");

                    b.Property<int>("BotWins")
                        .HasColumnType("int");

                    b.Property<float>("JunglePickRate")
                        .HasColumnType("real");

                    b.Property<int>("JunglePicks")
                        .HasColumnType("int");

                    b.Property<float>("JungleWinRate")
                        .HasColumnType("real");

                    b.Property<int>("JungleWins")
                        .HasColumnType("int");

                    b.Property<float>("MidPickRate")
                        .HasColumnType("real");

                    b.Property<int>("MidPicks")
                        .HasColumnType("int");

                    b.Property<float>("MidWinRate")
                        .HasColumnType("real");

                    b.Property<int>("MidWins")
                        .HasColumnType("int");

                    b.Property<float>("SuppPickRate")
                        .HasColumnType("real");

                    b.Property<int>("SuppPicks")
                        .HasColumnType("int");

                    b.Property<float>("SuppWinRate")
                        .HasColumnType("real");

                    b.Property<int>("SuppWins")
                        .HasColumnType("int");

                    b.Property<float>("TopPickRate")
                        .HasColumnType("real");

                    b.Property<int>("TopPicks")
                        .HasColumnType("int");

                    b.Property<float>("TopWinRate")
                        .HasColumnType("real");

                    b.Property<int>("TopWins")
                        .HasColumnType("int");

                    b.HasKey("ChampionName");

                    b.ToTable("ChampGameStats");
                });

            modelBuilder.Entity("BanMe.Domain.Entities.ChampMatchupStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnemyChampion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Picks")
                        .HasColumnType("int");

                    b.Property<float>("WinRate")
                        .HasColumnType("real");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChampMatchupStats");
                });

            modelBuilder.Entity("BanMe.Domain.Entities.Player", b =>
                {
                    b.Property<string>("PUUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionalRoute")
                        .HasColumnType("int");

                    b.HasKey("PUUID");

                    b.ToTable("PlayerPuuids");
                });

            modelBuilder.Entity("BanMe.Domain.Entities.ProcessedMatch", b =>
                {
                    b.Property<string>("MatchID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MatchID");

                    b.ToTable("ProcessedMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
